### ISSUE TITLE
can't generate ssr project

### ISSUE THREAD

**Issue by herve-ch** [nxarch/nxarch#35]
### Which @nxarch/* package(s) are the source of the bug?

ng-nest

### Is this a regression?

Yes

### Description

Hello, running 

`yarn nx generate @nxarch/ng-nest:init --ssrApp=my-angular-project --serverApp=my-nestjs-project`

in a clean nests + angular mono fail with error message:

 >  NX   Cannot read properties of undefined (reading 'replaceWithText')

Using nx 15.3.3

### Please provide the environment you discovered this bug in

```true
nx report :

Node : 18.12.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.3
   @nrwl/angular : 15.3.3
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 14.2.3
         @nxarch/ng-nest: 0.10.2
```

### Do you want to create a pull request?

No

**Comment by yackinn** [comment]
@herve-ch It's updated to support Angular Version 15. It should work now.

**Comment by herve-ch** [comment]
Hello, i tried again, installation seems fine now but i got an error when running nx run nest-api:serve-ssr:
`
TypeError: Cannot read properties of undefined (reading 'forEach')
    at C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\@nxarch\nest-nguniversal\src\lib\utils\setup-universal.utils.js:103:1
    at _ZoneDelegate.invokeTask (C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\zone.js\dist\zone-node.js:434:1)
    at Zone.runTask (C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\zone.js\dist\zone-node.js:205:1)
    at ZoneTask.invokeTask (C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\zone.js\dist\zone-node.js:516:1)     
    at ZoneTask.invoke (C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\zone.js\dist\zone-node.js:505:1)
    at data.args.<computed> (C:\Users\user\VisualCodeProjects\angular-nest\dist\apps\nest-api\webpack:\angular-nest\node_modules\zone.js\dist\zone-node.js:961:1)    
    at FSReqCallback.oncomplete (node:fs:188:23)
`
Tried on windows with nx report:
`Node : 16.15.0
   OS   : win32 x64
   yarn : 1.22.18
   
   nx : 15.4.2
   @nrwl/angular : 15.4.2
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : 15.4.2
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 15.0.0
         @nxarch/ng-nest: 0.11.3
`

**Comment by yackinn** [comment]
Are you sure the correct versions are installed? I just tried with a newly created nx workspace and newly installed nxarch

**Comment by herve-ch** [comment]
I dont know what is wrong, here is my repo, https://github.com/herve-ch/angular-nest

Thanks

**Comment by yackinn** [comment]
git clone
yarn install
yarn dev:server

It works.

The error means that there are no files created in your ui folder inside your dist directory. Can you confirm that?

**Comment by herve-ch** [comment]
yes i can confirm i dont have ui folder in dist
how to generate it??

**Comment by yackinn** [comment]
It should do that automatically when you start the process with dev:server.

Does the process have write permissions?

I can't test on a windows laptop.

**Comment by herve-ch** [comment]
i guess so, i'm on windows and other files are created in dist (front end : browser and ssr folders + nest api folder)

**Comment by yackinn** [comment]
I see what's wrong. The windows file path consists of backslashes. Let me write a fix.

**Comment by herve-ch** [comment]
just tried to run vscode with admin rights and still the same error when running dev:server, will try later on mac

**Comment by yackinn** [comment]
I released a new version but I haven't tested it on windows yet though.
I'll check tomorrow.

**Comment by herve-ch** [comment]
Thank you for your great work!
