### ISSUE TITLE
Can't use @nxarch/ng-nest to generate nest angular universal

### ISSUE THREAD

**Issue by herve-ch** [nxarch/nxarch#36]
### Which @nxarch/* package(s) are the source of the bug?

ng-nest

### Is this a regression?

Yes

### Description

Running `pnpm nx generate @nxarch/ng-nest:init --ssrApp=frontend --serverApp=backend` in a clean nestJS+angular mono repo generate an error

### Please provide a link to a minimal reproduction of the bug

https://github.com/herve-ch/angular-universal-nestjs.git

### Please provide the exception or error you saw

```true
NX   Cannot read properties of undefined (reading 'getBodyText')


TypeError: Cannot read properties of undefined (reading 'getBodyText')
    at updateBrowserMain (/Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/@nxarch+ng-nest@0.11.4_cdu6er22fmlaml75lildhu5nci/node_modules/@nxarch/ng-nest/src/generators/init/runners/update-browser-main.js:18:39)
    at /Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/@nxarch+ng-nest@0.11.4_cdu6er22fmlaml75lildhu5nci/node_modules/@nxarch/ng-nest/src/generators/init/generator.js:32:57
    at Generator.next (<anonymous>)
    at /Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
    at /Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/@nxarch+ng-nest@0.11.4_cdu6er22fmlaml75lildhu5nci/node_modules/@nxarch/ng-nest/src/generators/init/generator.js:27:30
    at Object.<anonymous> (/Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/nx@15.8.7/node_modules/nx/src/command-line/generate.js:249:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/VsCodeProjects/angular-universal-nestjs/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:164:62)
```

### Please provide the environment you discovered this bug in

```true
MacOS M1, NX 15.8.7, using pnpm manager
```

### Do you want to create a pull request?

No

**Comment by denny99** [comment]
I am having this issue too.

The problem is the main.ts from angular. Since Version 15.6 nx changed the main.ts file

```
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {AppModule} from './app/app.module';

function bootstrap() {
  platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch((err) => console.error(err));
}

if (document.readyState === 'complete') {
  bootstrap();
} else {
  document.addEventListener('DOMContentLoaded', bootstrap);
}
```

This is the original main.ts. This plugin searches for the bootstrap function that no longer exists. See the new code below

```typescript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));

```
